stages:
  - build
  - push

variables:

.dnd_template:
  image: docker:19.03
  services:
    - name: docker:19.03-dind
      command: ["--insecure-registry=docker-registry.devad.catalogic.us:5000"]
  before_script:
    - docker info
    - docker pull $DOCKER_IMAGE_NAME_FULL:latest || true
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_REGISTRY: docker-registry.devad.catalogic.us:5000
    DOCKER_OPTS: "--insecure-registry='docker-registry.devad.catalogic.us:5000'"
    DOCKER_DRIVER: overlay2

    DOCKER_IMAGE_NAME_SHORT: kubedrutil
    DOCKER_IMAGE_NAME_FULL:  $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME_SHORT

build:
  extends: .dnd_template
  stage: build
  script:
    - >
      docker build
      --cache-from $DOCKER_IMAGE_NAME_FULL:latest
      --tag $DOCKER_IMAGE_NAME_FULL:latest
      --tag $DOCKER_IMAGE_NAME_FULL:$CI_COMMIT_SHORT_SHA
      .
  only:
    refs:
      - master

push_tag:

push_tag:
  extends: .dnd_template
  stage: push
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $DOCKER_IMAGE_NAME_FULL:$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_IMAGE_NAME_FULL:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_NAME_FULL:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_NAME_FULL:$CI_COMMIT_TAG
  only:
    refs:
      - tags

