stages:
- lint
- build
- push

.lint_template:
  only:
    refs:
    - master
    - merge_requests
  except:
    variables:
    - $SKIP_LINT == "yes"

.dnd_template:
  image: docker:19.03
  services:
  - name: docker:19.03-dind
    command: ["--insecure-registry=docker-registry.devad.catalogic.us:5000"]
  before_script:
  - apk add --no-cache make
  - docker info
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_OPTS: "--insecure-registry='docker-registry.devad.catalogic.us:5000'"
    DOCKER_DRIVER: overlay2

    DOCKER_REGISTRY: docker-registry.devad.catalogic.us:5000

    DOCKER_KUBEDRUTIL_IMAGE_NAME_SHORT: kubedrutil
    DOCKER_KUBEDRUTIL_IMAGE_NAME_LONG: $DOCKER_REGISTRY/$DOCKER_KUBEDRUTIL_IMAGE_NAME_SHORT
    DOCKER_KUBEDRUTIL_IMAGE_TAG: $CI_COMMIT_SHORT_SHA

lint_yaml:
  extends: .lint_template
  stage: lint
  image: sdesbure/yamllint
  script:
  - yamllint .

build_image:
  extends: .dnd_template
  stage: build
  script:
  - make build
  - docker push $DOCKER_KUBEDRUTIL_IMAGE_NAME_LONG:$DOCKER_KUBEDRUTIL_IMAGE_TAG

push_latest:
  extends: .dnd_template
  stage: push
  variables:
    GIT_STRATEGY: none
  script:
  - make docker_push_latest
  only:
    refs:
    - master

push_tag:
  extends: .dnd_template
  stage: push
  variables:
    GIT_STRATEGY: none

    DOCKER_REGISTRY: catalogicsoftware
  before_script:
  - apk add --no-cache make
  - docker info
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
  script:
  - make docker_push_tags
  only:
    refs:
    - tags
