stages:
  - lint
  - build
  - push

.dnd_template:
  image: docker:19.03
  services:
    - name: docker:19.03-dind
      command: ["--insecure-registry=docker-registry.devad.catalogic.us:5000"]
  before_script:
    - docker info
    - cd container
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_REGISTRY: docker-registry.devad.catalogic.us:5000
    DOCKER_OPTS: "--insecure-registry='docker-registry.devad.catalogic.us:5000'"
    DOCKER_DRIVER: overlay2

    DOCKER_IMAGE_NAME_SHORT: kubedrutil
    DOCKER_IMAGE_NAME_LONG: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME_SHORT

yaml_lint:
  stage: lint
  image: sdesbure/yamllint
  script:
    - yamllint .
  only:
    changes:
      - "**/*.yml"
      - "**/*.yaml"

build_image:
  extends: .dnd_template
  stage: build
  script:
    - docker pull $DOCKER_IMAGE_NAME_LONG:latest || true
    - >
      docker build
      --cache-from $DOCKER_IMAGE_NAME_LONG:latest
      --tag $DOCKER_IMAGE_NAME_LONG:$CI_COMMIT_SHORT_SHA
      .
    - docker push $DOCKER_IMAGE_NAME_LONG:$CI_COMMIT_SHORT_SHA
  only:
    changes:
      - container/**/*

push_latest:
  extends: .dnd_template
  stage: push
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $DOCKER_IMAGE_NAME_LONG:$CI_COMMIT_SHORT_SHA || true
    - docker tag $DOCKER_IMAGE_NAME_LONG:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_NAME_LONG:latest
    - docker push $DOCKER_IMAGE_NAME_LONG:latest
  only:
    refs:
      - master
    changes:
      - container/**/*

push_tag:
  extends: .dnd_template
  stage: push
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $DOCKER_IMAGE_NAME_LONG:$CI_COMMIT_SHORT_SHA || true
    - docker tag $DOCKER_IMAGE_NAME_LONG:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_NAME_LONG:$CI_COMMIT_TAG
    - docker push $DOCKER_IMAGE_NAME_LONG:$CI_COMMIT_TAG
  only:
    refs:
      - tags
    changes:
      - container/**/*
