image: docker:19.03
services:
  - name: docker:19.03-dind
    command: ["--insecure-registry=docker-registry.devad.catalogic.us:5000"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_REGISTRY: docker-registry.devad.catalogic.us:5000
  DOCKER_OPTS: "--insecure-registry='docker-registry.devad.catalogic.us:5000'"
  DOCKER_DRIVER: overlay2

  DOCKERFILE_NAME_SHORT: kubedrutil
  DOCKERFILE_NAME_FULL: $DOCKER_REGISTRY/$DOCKERFILE_NAME_SHORT

stages:
  - build

variables:

before_script:
  - docker info
  - docker pull $DOCKERFILE_NAME_FULL:latest || true

master:
  stage: build
  script:
    - >
      docker build
        --pull
        --cache-from $DOCKERFILE_NAME_FULL:latest
        --tag $DOCKERFILE_NAME_FULL:$CI_COMMIT_SHORT_SHA